//
//  VoiceProvider.swift
//  SwiftHablare
//
//  Protocol defining voice provider capabilities
//

import Foundation
#if canImport(SwiftUI)
import SwiftUI
#endif

/// Protocol defining voice provider capabilities
public protocol VoiceProvider: Sendable {
    /// Unique identifier for the provider
    var providerId: String { get }

    /// Display name for the provider
    var displayName: String { get }

    /// Whether this provider requires an API key
    var requiresAPIKey: Bool { get }

    /// MIME type of audio generated by this provider (e.g., "audio/x-aiff", "audio/mpeg")
    var mimeType: String { get }

    /// Check if the provider is properly configured
    func isConfigured() -> Bool

    /// Fetch available voices from the provider
    /// - Parameter languageCode: Optional language code to filter voices (e.g., "en", "es", "fr").
    ///   If not provided, uses system language code as default.
    func fetchVoices(languageCode: String) async throws -> [Voice]

    /// Generate audio data from text using a specific voice
    /// - Parameters:
    ///   - text: The text to convert to speech
    ///   - voiceId: The voice identifier to use
    ///   - languageCode: The language code for generation (e.g., "en", "es", "fr").
    ///     Defaults to system language if not provided.
    func generateAudio(text: String, voiceId: String, languageCode: String) async throws -> Data

    /// Estimate the duration (in seconds) of audio that would be generated from the given text
    func estimateDuration(text: String, voiceId: String) async -> TimeInterval

    /// Check if a specific voice is available for this provider
    /// - Parameter voiceId: The voice identifier to check
    /// - Returns: True if the voice is available, false otherwise
    func isVoiceAvailable(voiceId: String) async -> Bool

#if canImport(SwiftUI)
    /// Build the SwiftUI configuration panel for this provider
    ///
    /// Implementations should present any fields necessary to configure the
    /// provider (e.g., API keys). The view must invoke the `onConfigured`
    /// callback with `true` when configuration succeeds, or `false` if it
    /// fails or is cancelled.
    ///
    /// - Parameter onConfigured: Callback invoked when configuration
    ///   completes.
    /// - Returns: A type-erased SwiftUI view representing the configuration
    ///   panel.
    @MainActor
    func makeConfigurationView(onConfigured: @escaping (Bool) -> Void) -> AnyView
#endif
}

// MARK: - Default Language Code Extensions

extension VoiceProvider {
    /// Fetch available voices using system language code as default
    public func fetchVoices() async throws -> [Voice] {
        let languageCode = Locale.current.language.languageCode?.identifier ?? "en"
        return try await fetchVoices(languageCode: languageCode)
    }

    /// Generate audio using system language code as default
    public func generateAudio(text: String, voiceId: String) async throws -> Data {
        let languageCode = Locale.current.language.languageCode?.identifier ?? "en"
        return try await generateAudio(text: text, voiceId: voiceId, languageCode: languageCode)
    }
}

/// Voice provider errors
public enum VoiceProviderError: LocalizedError, Sendable {
    case notConfigured
    case networkError(String)
    case invalidResponse
    case unsupportedProvider
    case notSupported
    case invalidRequest(String)

    public var errorDescription: String? {
        switch self {
        case .notConfigured:
            return "Voice provider is not configured. Please check your settings."
        case .networkError(let message):
            return "Network error: \(message)"
        case .invalidResponse:
            return "Invalid response from voice provider"
        case .unsupportedProvider:
            return "Unsupported voice provider"
        case .notSupported:
            return "Audio generation is not supported on this platform"
        case .invalidRequest(let message):
            return "Invalid request: \(message)"
        }
    }
}
